---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.4.3.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
imageUrl: "https://raw.githubusercontent.com/TheXaman/jellyfin-plugin-languageTags/refs/heads/main/Images/logo.png"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.4.3.1\",\"feat: fixed missing subtitle language tags for collections,  addresses #21\",\"Update build.yaml and manifest-preview.json for preview version 0.4.3.0-preview\",\"Bump version to 0.4.3.0\",\"feat: implement audio language tag addition by name in LanguageTagsManager, addresses  #21\"]"
