---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.1.4.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.1.4.0\",\"Update README.md to include installation instructions\",\"Update build.yaml and manifest.json for release version 0.1.3.5\",\"Bump version to 0.1.3.5\",\"fixed build.yaml\",\"Update build.yaml and manifest.json for release version 0.1.3.4\",\"Bump version to 0.1.3.4\",\"updated build.yaml creation to ensure jellyfin can read the resulting meta.json\",\"Update build.yaml and manifest.json for release version 0.1.3.3\",\"Bump version to 0.1.3.3\",\"another test at tag creation\",\"Update build.yaml and manifest.json for release version 0.1.3.2\",\"Bump version to 0.1.3.2\",\"Refactored release workflow to use environment variable for tag name\"]"
