---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.4.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
imageUrl: "https://raw.githubusercontent.com/TheXaman/jellyfin-plugin-languageTags/refs/heads/main/Images/logo.png"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.4.1.0\",\"fix: changed how movies are retrieved from collections, fixes #21\",\"fix: \\\"Force full refresh for tv shows\\\" triggering a complete refresh, fixes #17 fix: Change return statements to continue in library processing for null checks\",\"Update build.yaml and manifest-preview.json for preview version 0.4.0.0-preview\",\"Bump version to 0.4.0.0\",\"feat: Add non-media tagging functionality with configuration options\",\"Remove commas from language names to avoid tag splitting issue in Parental Control (#23)\",\"feat: Enhance language checkbox display with ISO codes and improve selected language chips\",\"add silent movies to whitelist, addresses #22\"]"
