---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.2.1.2"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
imageUrl: "https://raw.githubusercontent.com/TheXaman/jellyfin-plugin-languageTags/refs/heads/main/Images/logo.png"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.2.1.2\",\"Fix changelog special character handling using environment variable\",\"Remove outdated preview version entries from manifest files\",\"Fix changelog formatting to handle special characters in workflow\",\"Bump version to 0.2.1.1\",\"Remove redundant step to get last release tag in release workflow\",\"Bump version to 0.2.1.0\",\"- Migrate from .NET 8.0 to .NET 9.0 - Replace deprecated GetItemList() with QueryItems() API - Update TaskTriggerInfo to use TaskTriggerInfoType.IntervalTrigger - Add null path handling for video files in Jellyfin 10.11.0 - Filter out virtual items from TV show queries - Refactor file path validation logic - Add preview release workflow support\\\"\",\"Update build.yaml and manifest.json for release version 0.2.0.1\",\"Update build.yaml and manifest.json for release version 0.2.0.1\",\"Update build.yaml to target .NET 9.0 framework\",\"Bump version to 0.2.0.1\",\"Enhance release workflow: update version handling, target .NET 9.0, and improve changelog generation\",\"- Replace deprecated GetItemList() with QueryItems() API - Update TaskTriggerInfo to use TaskTriggerInfoType.IntervalTrigger\",\"- Update to target Jellyfin 10.11.0 - Migrate from .NET 8.0 to .NET 9.0\"]"
