---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.4.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
imageUrl: "https://raw.githubusercontent.com/TheXaman/jellyfin-plugin-languageTags/refs/heads/main/Images/logo.png"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.4.0.0\",\"feat: Add non-media tagging functionality with configuration options\",\"Remove commas from language names to avoid tag splitting issue in Parental Control (#23)\",\"feat: Enhance language checkbox display with ISO codes and improve selected language chips\",\"add silent movies to whitelist, addresses #22\",\"Update build.yaml and manifest-preview.json for preview version 0.3.0.0-preview\",\"Bump version to 0.3.0.0\",\"feat: Use language names in tags and add visual language selector\",\"Add customizable prefixes for audio and subtitle language tags with validation\",\"Refactor: Simplify audio and subtitle language tag handling by introducing helper methods\",\"Refactor: Replace FFmpeg with MediaStreams API for 10-100x performance boost\"]"
