---
name: "Language Tags"
guid: "e6ee25c2-d12c-4382-a48c-66ee9c1c33cb"
version: "0.2.0.1"
targetAbi: "10.11.0.0"
framework: "net8.0"
overview: "This plugin automatically adds language tags to the media."
description: |
  "This plugin automatically scans the libraries and adds language tags to the media items.\n The languages are extracted from the audio tracks. Media types covered are movies,\n tv shows / series and collections."
category: "General"
owner: "TheXaman"
imageUrl: "https://raw.githubusercontent.com/TheXaman/jellyfin-plugin-languageTags/refs/heads/main/Images/logo.png"
artifacts:
  - "Jellyfin.Plugin.LanguageTags.dll"
changelog: "[\"Bump version to 0.2.0.1\",\"Fix preview release workflow - use base version for build\",\"Add preview release support and manifest file\",\"Enhance release workflow: update version handling, target .NET 9.0, and improve changelog generation\",\"- Replace deprecated GetItemList() with QueryItems() API - Update TaskTriggerInfo to use TaskTriggerInfoType.IntervalTrigger\",\"- Update to target Jellyfin 10.11.0 - Migrate from .NET 8.0 to .NET 9.0\",\"Merge pull request #15 from Rand0mB0y:patch-1\",\"Update README.md to clarify external subtitles note and switched to PowerRename tool\",\"manual cleanup of the changelogs\",\"Update build.yaml and manifest.json for release version 0.1.8.0\",\"Bump version to 0.1.8.0\",\"Make sure to only add 3 letter language tags, even if the extracted tags for a subtitle file are 2 letter codes\",\"Make sure external subtitles are scanned daily if subtitle extraction is enabled, see #13\",\"Fixes language tag refresh for external subtitles due to invalid stripping of nonexistent prefixes, see #13\",\"Make sure all tags for external subtitles are lower case. Fixes #12\",\"Update README.md\"]"
