name: Release

on:
  push:
    paths:
      - VERSION
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures full history for changelog generation

      - name: Get version from VERSION file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Generate Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - name: Format Changelog to JSON
        id: format_changelog
        run: |
          formatted_changelog=$(echo "${{ steps.changelog.outputs.changelog }}" | sed -E 's/ - [a-f0-9]{7} //' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "FORMATTED_CHANGELOG=$formatted_changelog" >> $GITHUB_ENV

      - name: Update `build.yaml`
        run: |
          yq -P eval '
            .version = strenv(VERSION) |
            .targetAbi = "10.10.0.0" |
            .changelog = (strenv(FORMATTED_CHANGELOG) | fromjson)
          ' build.yaml > build.tmp.yaml && mv build.tmp.yaml build.yaml

      - name: Print build.yaml
        run: |
          echo "Updated build.yaml:"
          cat build.yaml

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Build Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@v0.5.0
        id: jprm
        with:
          dotnet-target: net8.0

      - name: Generate Release Checksums
        run: |
          hash="$(md5sum ${{ steps.jprm.outputs.artifact }} | cut -d ' ' -f 1)"
          echo "$hash $(basename ${{ steps.jprm.outputs.artifact }})" >> checksums.md5
          echo "CHECKSUM=$hash" >> $GITHUB_ENV

      - name: Update `manifest.json`
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sourceUrl="https://github.com/TheXaman/jellyfin-plugin-languageTags/releases/download/v$VERSION/language-tags_$VERSION.zip"
          formatted_changelog=$(echo "$FORMATTED_CHANGELOG" | jq -r '.[]' | sed 's/^/- /')
          jq --arg strippedversion "$VERSION" \
            --arg changelog "$formatted_changelog" \
            --arg checksum "$CHECKSUM" \
            --arg timestamp "$timestamp" \
            --arg sourceUrl "$sourceUrl" \
            '.[0].versions |= [{
              version: $strippedversion,
              changelog: $changelog,
              targetAbi: "10.10.0.0",
              sourceUrl: $sourceUrl,
              checksum: $checksum,
              timestamp: $timestamp
            }] + .' \
            manifest.json > manifest.tmp.json && mv manifest.tmp.json manifest.json

      - name: Commit Updated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add build.yaml manifest.json
          git commit -m "Update build.yaml and manifest.json for release version $VERSION"
          git push origin HEAD:main

      - name: Create Tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo "Creating tag v${VERSION}"
          git tag -a "v${VERSION}" -m "Release version v${VERSION}"
          git push origin "v${VERSION}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          VERSION: ${{ env.VERSION }}
        with:
          tag_name: "v${VERSION}"
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            checksums.md5
            ${{ steps.jprm.outputs.artifact }}
